### ISSUE TITLE
Plugin crushes on jupyter notebooks

### ISSUE THREAD

**Issue by sam-chisholm** [leinardi/pylint-pycharm#101]
### Step 1: Are you in the right place?
- [ ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [ ] I have verified that I am using the latest version of the plugin.

### Step 2: Describe your environment
 - Plugin version: 0.16.2
 - PyCharm/IDEA version: Professional Edition 2023.2.3
 - Pylint version: 3.0.2

#### Observed Results:
The scan failed due to an exception: Illegal state: filesToScan is empty com.leinardi.pycharm.pylint.exception.PylintPluginException: Illegal state: filesToScan is empty   at com.leinardi.pycharm.pylint.plapi.PylintRunner.scan(PylintRunner.java:233)   at com.leinardi.pycharm.pylint.checker.ScanFiles.scan(ScanFiles.java:109)   at com.leinardi.pycharm.pylint.checker.ScanFiles.checkFiles(ScanFiles.java:100)   at com.leinardi.pycharm.pylint.checker.ScanFiles.call(ScanFiles.java:74)   at com.leinardi.pycharm.pylint.PylintAnnotator.doAnnotate(PylintAnnotator.java:115)   at com.leinardi.pycharm.pylint.PylintAnnotator.doAnnotate(PylintAnnotator.java:62)   at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:207)   at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:201)   at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$0(ExternalToolPass.java:164)   at com.intellij.codeInsight.daemon.impl.ExternalToolPass.runChangeAware(ExternalToolPass.java:266)   at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$2(ExternalToolPass.java:164)   at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)   at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)   at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)   at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)   at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)   at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)   at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)   at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:360)   at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:162)   at com.intellij.util.ui.update.Update.runUpdate(Update.java:114)   at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:348)   at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:338)   at com.intellij.util.ui.update.MergingUpdateQueue.doFlush(MergingUpdateQueue.java:295)   at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:277)   at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:246)   at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:254)   at com.intellij.util.Alarm$Request.runSafely(Alarm.java:373)   at com.intellij.util.Alarm$Request.run(Alarm.java:360)   at com.intellij.util.concurrency.Propagation.contextAwareCallable$lambda$2(propagation.kt:328)   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)   at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)   at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:249)   at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)   at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:227)   at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:218)   at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:215)   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)   at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)   at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by leinardi** [comment]
Hi everyone,  

A new developer, `@szabope`, has created a full rewrite of this PyLint plugin. The new plugin is actively maintained and addresses many of the issues found here.  

You can find the new plugin on the JetBrains Plugin Marketplace: [PyLint Plugin](https://plugins.jetbrains.com/plugin/26358-pylint/versions/stable/668924) 
The source code is available here: [GitHub Repository](https://github.com/szabope/pylint-pycharm-plugin)

Please give it a try, as the old plugin will soon be archived.  

Thank you!
