### ISSUE TITLE
the last version can not work at windows' pycharm(pycharm ver 2024.1)

### ISSUE THREAD

**Issue by notinmood** [leinardi/pylint-pycharm#104]
this is stacktrace information:
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.leinardi.pycharm.pylint.actions.StopCheck' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.leinardi.pycharm.pylint]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

**Comment by JoeKae** [comment]
This error occurs whenever I link a .pylintrc file.
Pylint continues to use its default settings and throws the reported stack trace.

**Comment by dclowd9901** [comment]
We don't use a `.pylintrc` file, and still receive this error.

**Comment by leinardi** [comment]
Hi everyone,  

A new developer, `@szabope`, has created a full rewrite of this PyLint plugin. The new plugin is actively maintained and addresses many of the issues found here.  

You can find the new plugin on the JetBrains Plugin Marketplace: [PyLint Plugin](https://plugins.jetbrains.com/plugin/26358-pylint/versions/stable/668924) 
The source code is available here: [GitHub Repository](https://github.com/szabope/pylint-pycharm-plugin)

Please give it a try, as the old plugin will soon be archived.  

Thank you!
