### ISSUE TITLE
pylint plugin crashed see stack trace

### ISSUE THREAD

**Issue by ravi005e** [leinardi/pylint-pycharm#111]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.leinardi.pycharm.pylint.actions.ScanCurrentFile' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.leinardi.pycharm.pylint]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

### Step 2: Describe your environment
 - Plugin version: `0.16.2`
 - PyCharm/IDEA version: `2024.23`

**Comment by leinardi** [comment]
This issue was fixed in version 0.16.3, please update to the latest version: https://plugins.jetbrains.com/plugin/11084-pylint/edit/versions

**Comment by ravi005e** [comment]
thanks
