### ISSUE TITLE
Exception in Intellij 2018.2.4 with pylint

### ISSUE THREAD

**Issue by pekkla** [leinardi/pylint-pycharm#30]
The plugin works fine, but the following exception keeps coming all the time: 

java.lang.Throwable: Error while checking Pylint path: No config file found, using default configuration
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:123)
	at com.leinardi.pycharm.pylint.plapi.PylintRunner.isPylintPathValid(PylintRunner.java:98)
	at com.leinardi.pycharm.pylint.plapi.PylintRunner.checkPylintAvailable(PylintRunner.java:176)
	at com.leinardi.pycharm.pylint.plapi.PylintRunner.checkPylintAvailable(PylintRunner.java:150)
	at com.leinardi.pycharm.pylint.PylintInspection.inspectFile(PylintInspection.java:76)
	at com.leinardi.pycharm.pylint.PylintInspection.lambda$checkFile$0(PylintInspection.java:65)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:337)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by leinardi** [comment]
Hi, I added some logs with the last update that are probably showing as errors. I am a little busy in these days, I hope to be able to fix soon.

But thanks for the report :+1:

**Comment by AlmightyOatmeal** [comment]
### Step 1: Are you in the right place?
- [X] I have verified there are no duplicate active or recent bugs, questions, or requests
- [X] I have verified that I am using the latest version of the plugin.

### Step 2: Describe your environment
 - Plugin version: `0.10.2`
 - PyCharm/IDEA version: `2019.1 (191.4212.43)`
 - Pylint version: `1.9.4`

### Step 3: Describe the problem:
#### Steps to reproduce:

  1. Installed PyCharm 2019.1
  2. Installed plugin
  3. Exception occurred with a project open


#### Observed Results:

An exception.

```
java.lang.Throwable: Error while checking Pylint path: No config file found, using default configuration
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.leinardi.pycharm.pylint.plapi.PylintRunner.isPylintPathValid(PylintRunner.java:98)
	at com.leinardi.pycharm.pylint.plapi.PylintRunner.checkPylintAvailable(PylintRunner.java:176)
	at com.leinardi.pycharm.pylint.plapi.PylintRunner.scan(PylintRunner.java:229)
	at com.leinardi.pycharm.pylint.checker.ScanFiles.scan(ScanFiles.java:108)
	at com.leinardi.pycharm.pylint.checker.ScanFiles.checkFiles(ScanFiles.java:100)
	at com.leinardi.pycharm.pylint.checker.ScanFiles.call(ScanFiles.java:74)
	at com.leinardi.pycharm.pylint.PylintInspection.inspectFile(PylintInspection.java:88)
	at com.leinardi.pycharm.pylint.PylintInspection.lambda$checkFile$0(PylintInspection.java:65)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:341)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
  
![Screenshot: PyCharm: Exception](https://www.dropbox.com/s/d7wuqywu87xt7jv/Screen%20Shot%202019-01-25%20at%2019.15.50.png?dl=0&raw=1)


#### Expected Results:

Well, not having the problem is the expected result.

#### Relevant Code:
N/A

-----

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G4015
```

```
$ which pylint
/usr/local/bin/pylint
```

```
$ pylint --version
No config file found, using default configuration
pylint 1.9.4,
astroid 1.6.5
Python 2.7.10 (default, Oct  6 2017, 22:29:07)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

```
$ env | sort
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.ISrPDdcSh2/Render
COLORFGBG=7;0
COLORTERM=truecolor
GOPATH=/Users/jamie/Dropbox/data.Go.GOPATH
HOME=/Users/jamie
HOMEBREW_CASK_OPTS=--caskroom=/opt/homebrew-cask/Caskroom
HOMEBREW_GITHUB_API_TOKEN=5b78e86a7b98042b02a930a88e671ee5928622d2
ITERM_PROFILE=Default
ITERM_SESSION_ID=w0t6p0:DD97546D-314F-4480-AC66-89D957206107
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_72.jdk/Contents/Home
JRE_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_72.jdk/Contents/Home
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LESS=-R
LOGNAME=jamie
LSCOLORS=Gxfxcxdxbxegedabagacad
OLDPWD=/Users/jamie
PAGER=less
PATH=/Users/jamie/perl5/bin:/opt/brew/opt/python/libexec/bin:/usr/local/opt/go/libexec/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/qt/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:~/src/arc/arcanist/bin:Library/Python/2.7/bin:/Applications/010 Editor.app/Contents/CmdLine:/Users/jamie/Dropbox/data.Go.GOPATH/bin:/opt/metasploit-framework/bin
PERL5LIB=/Users/jamie/perl5/lib/perl5
PERL_LOCAL_LIB_ROOT=/Users/jamie/perl5
PERL_MB_OPT=--install_base "/Users/jamie/perl5"
PERL_MM_OPT=INSTALL_BASE=/Users/jamie/perl5
PWD=/Users/jamie
PYTHONDONTWRITEBYTECODE=true
SHELL=/bin/zsh
SHLVL=1
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.Mplzk3vfZV/Listeners
SSLKEYLOGFILE=/Users/jamie/.sslkeylog.log
TERM=xterm-256color
TERM_PROGRAM=iTerm.app
TERM_PROGRAM_VERSION=3.2.7beta4
TERM_SESSION_ID=w0t6p0:DD97546D-314F-4480-AC66-89D957206107
TMPDIR=/var/folders/gv/7grq_ggx73j6f56ljn37_52h0000gn/T/
USER=jamie
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
ZSH=/Users/jamie/.oh-my-zsh
_=/usr/bin/env
__CF_USER_TEXT_ENCODING=0x0:0:0
```

```
$ python --version
Python 2.7.10
```

```
$ python
Python 2.7.10 (default, Oct  6 2017, 22:29:07)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

![Screenshot: PyCharm: Version](https://www.dropbox.com/s/k86zlrfr1ha960s/Screen%20Shot%202019-01-25%20at%2019.18.20.png?dl=0&raw=1)
