### ISSUE TITLE
The scan failed due to an exception: null

### ISSUE THREAD

**Issue by shengulong** [leinardi/pylint-pycharm#33]
Unexpected Exception Caught
			The scan failed due to an exception: null
			java.lang.NullPointerException
			at com.leinardi.pycharm.pylint.PylintInspection.lambda$inspectFile$1(PylintInspection.java:90)
			at java.util.ArrayList.removeIf(ArrayList.java:1407)
			at com.leinardi.pycharm.pylint.PylintInspection.lambda$inspectFile$2(PylintInspection.java:89)
			at java.util.HashMap$Values.forEach(HashMap.java:980)
			at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
			at com.leinardi.pycharm.pylint.PylintInspection.inspectFile(PylintInspection.java:89)
			at com.leinardi.pycharm.pylint.PylintInspection.lambda$checkFile$0(PylintInspection.java:65)
			at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:337)
			at java.util.concurrent.FutureTask.run(FutureTask.java:266)
			at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPool... (show balloon)

**Comment by leinardi** [comment]
Please fill all the bug report information requested by the template.
