### ISSUE TITLE
Pylint inspect java error

### ISSUE THREAD

**Issue by cbroque** [leinardi/pylint-pycharm#54]
### Step 1: Are you in the right place?
- [x ] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x ] I have verified that I am using the latest version of the plugin.

### Step 2: Describe your environment
 - Plugin version: 0.11.1
 - PyCharm/IDEA version: 2019.2
 - Pylint version: 1.6.5

### Step 3: Describe the problem:
Next error is gotten when you run python code inspection:
Unexpected Exception Caught
				The scan failed due to an exception: null
				java.lang.NullPointerException
				at com.leinardi.pycharm.pylint.PylintInspection.lambda$inspectFile$1(PylintInspection.java:90)
				at java.base/java.util.ArrayList.removeIf(ArrayList.java:1701)
				at java.base/java.util.ArrayList.removeIf(ArrayList.java:1689)
				at com.leinardi.pycharm.pylint.PylintInspection.lambda$inspectFile$2(PylintInspection.java:89)
				at java.base/java.util.HashMap$Values.forEach(HashMap.java:976)
				at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1083)
				at com.leinardi.pycharm.pylint.PylintInspection.inspectFile(PylintInspection.java:89)
				at com.leinardi.pycharm.pylint.PylintInspection.lambda$checkFile$0(PylintInspection.java:65)
				at com.intellij.openapi.application.impl.ApplicationImpl$2.call(ApplicationImpl.java:322)
				at java.base/java.util.concurr... (show balloon)

#### Steps to reproduce:

  1. Install pylint plugin from settings.
  2. Check if the path is correct and fix it if necesary on other settings
  3. Run code inspection

#### Observed Results:

  * You get the above java error.
  

#### Expected Results:
Pylint inspection results

  * 

#### Relevant Code:

```java
System.out.println("Hello, world!");
```

```Gradle
java.lang.RuntimeException: This is an example Exception log
    at com.leinardi.HelloWorld
    at com.leinardi.HelloWorld$ThisIsNotARealLog
    at bigcorporate.app.Instrumentation.callActivityOnResume(Instrumentation.kt)
```

**Comment by cbroque** [comment]
I managed to solve this.
I tried to upgrade the pylint version on the project interpreter settings, I was unable to do it, I had to force the upgrade to version 1.9.5 from cli, using the pip inside the project interpreter folder.

After that all is working fine

**Comment by cbroque** [comment]
You can close this issue
