### ISSUE TITLE
pylint plugin incompatible with IntelliJ IDEA v. 2020.2 on Catalina

### ISSUE THREAD

**Issue by jgoldste** [leinardi/pylint-pycharm#71]
pylint can be executed from the command line but not within IntelliJ. Please see the [bug report](https://youtrack.jetbrains.com/issue/PY-44314?clearDraft=true&description=%0A%0AIU-202.6948.69,%20JRE%2011.0.8%2B10-b944.31x64%20JetBrains%20s.r.o.,%20OS%20Mac%20OS%20X(x86_64)%20v10.15.4,%20screens%201344x840,%201920x1200;%20Retina&p=IDEA-249932) I submitted to JetBrains, who sent me to you. Thank you.

**Comment by phazebroek** [comment]
I'm on IntelliJ ultimate 2020.3 beta but also unable to run this plugin.
I'm getting the following error when I hit the test button:
`Pylint Plugin: Failure: executable "/Users/pim/projects/personal/rcm/venv/bin/pylint" not found`

Also tried the /usr/local/bin/pylint executable but doesn't work either.

I'm certain the path is fine because:
```
$ where pylint
/Users/pim/projects/personal/rcm/venv/bin/pylint
/usr/local/bin/pylint
/usr/local/bin/pylint
```
And yes, the file is executable:
```
 ~/projects/personal/rcm/venv/bin $ ls -al | grep pylint
-rwxr-xr-x   1 pim  staff    251 Nov 24 20:07 epylint
-rwxr-xr-x   1 pim  staff    249 Nov 24 20:07 pylint
```

**Comment by larsschaps** [comment]
Same here:
IntelliJ IDEA 2020.3.1 (Ultimate Edition)
Build #IU-203.6682.168, built on December 29, 2020
[...]
Runtime version: 11.0.9.1+11-b1145.63 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.8.0-36-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1919M
Cores: 8
...

18:08	Pylint Plugin (Unable to run Pylint)
Pylint is installed inside the project environment but the plugin is not able to run it. If you just installed it try to run File -> Synchronize or restart your IDE. If the problem persists you may need to manually enter the path to the Pylint executable inside the Plugin settings.
18:08	Pylint Plugin: Failure: executable "<path to project here>/venv/bin/pylint" not found

**Comment by larsschaps** [comment]
> com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "/home/lars/.jdks/adopt-openj9-1.8.0_282": error=13, Permission denied
> 	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:380)
> 	at com.leinardi.pycharm.pylint.plapi.PylintRunner.isPylintPathValid(PylintRunner.java:94)

The "/home/lars/.jdks/adopt-openj9-1.8.0_282" is just the directory. Might that be the problem? You can't run a directory?

**Comment by larsschaps** [comment]
Yes.... project SDK was a JDK, needs to be Python interpreter...

**Comment by leinardi** [comment]
Hi everyone,  

A new developer, `@szabope`, has created a full rewrite of this PyLint plugin. The new plugin is actively maintained and addresses many of the issues found here.  

You can find the new plugin on the JetBrains Plugin Marketplace: [PyLint Plugin](https://plugins.jetbrains.com/plugin/26358-pylint/versions/stable/668924) 
The source code is available here: [GitHub Repository](https://github.com/szabope/pylint-pycharm-plugin)

Please give it a try, as the old plugin will soon be archived.  

Thank you!
