### ISSUE TITLE
Exception while commiting to hg Repo

### ISSUE THREAD

**Issue by Xtrem532** [leinardi/pylint-pycharm#73]
### Step 1: Are you in the right place?
- [x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x] I have verified that I am using the latest version of the plugin.

### Step 2: Describe your environment
 - Plugin version: `0.12.2`
 - PyCharm/IDEA version: `PyCharm 2020.2.2 (Community Edition)  Build #PC-202.7319.64, built on September 16, 2020`
 - Pylint version: `2.6.0`  

Note: Plugin was manually downloaded (from https://plugins.jetbrains.com/) and installed

#### Steps to reproduce:

  1. Have PyLint Toolbar open
  2. Commit to hg Repo using Commit Toolbar (Alt-0) (using default mercurial plugin version `202.7319.64`)
  3. Receive Exception in eventlog (before the "X files committed" message from the VCS plugin)

#### Exception:

```Gradle
com.leinardi.pycharm.pylint.exception.PylintPluginException: Illegal state: filesToScan is empty   at 
com.leinardi.pycharm.pylint.plapi.PylintRunner.scan(PylintRunner.java:238)   at 
com.leinardi.pycharm.pylint.checker.ScanFiles.scan(ScanFiles.java:108)   at 
com.leinardi.pycharm.pylint.checker.ScanFiles.checkFiles(ScanFiles.java:100)   at 
com.leinardi.pycharm.pylint.checker.ScanFiles.call(ScanFiles.java:74)   at 
com.leinardi.pycharm.pylint.checker.ScanFiles.call(ScanFiles.java:46)   at 
com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:268)   at 
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)   at 
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)   at 
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)   at 
java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)   at 
java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)   at 
java.base/java.security.AccessController.doPrivileged(Native Method)   at 
java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)   at 
java.base/java.lang.Thread.run(Thread.java:834) 
```

#### Eventlog:

```
01.10.2020
14:57	Unexpected Exception Caught
			The scan failed due to an exception: Illegal state: filesToScan is empty
			com.leinardi.pycharm.pylint.exception.PylintPluginException: Illegal state: filesToScan is empty

			at com.leinardi.pycharm.pylint.plapi.PylintRunner.scan(PylintRunner.java:238)

			at com.leinardi.pycharm.pylint.checker.ScanFiles.scan(ScanFiles.java:108)

			at com.leinardi.pycharm.pylint.checker.ScanFiles.checkFiles(ScanFiles.java:100)

			at com.leinardi.pycharm.pylint.checker.ScanFiles.call(ScanFiles.java:74)

			at com.leinardi.pycharm.pylint.checker.ScanFiles.call(ScanFiles.java:46)

			at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:268)

			at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)

			at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

			at java.base/java.util.concurrent.ThreadPoolEx... (show balloon)

14:57	1 file committed: <redacted Commitmessage>
```

**Comment by seb-buch** [comment]
Hi,

same happens when commiting to a git repo. I suspect this hapens for virtually all the VCS.

- Plugin version: `0.12.2`
- PyCharm version: `2020.3 (Professional Edition), Build #PY-203.5981.165, built on December 7, 2020`
- OS: `Windows 10 10.0`
- Pylint version: `2.6.0`

**Comment by Magicbeanbuyer** [comment]
Hey, 

I got the same problem.

## Version
pylint 2.8.2
Python 3.8.2
plugin 0.12.2


## Event Log
```
Unexpected Exception Caught
The scan failed due to an exception: Illegal state: filesToScan is empty
com.leinardi.pycharm.pylint.exception.PylintPluginException: Illegal state: filesToScan is empty   at
com.leinardi.pycharm.pylint.plapi.PylintRunner.scan(PylintRunner.java:238)   at
com.leinardi.pycharm.pylint.checker.ScanFiles.scan(ScanFiles.java:108)   at
com.leinardi.pycharm.pylint.checker.ScanFiles.checkFiles(ScanFiles.java:100)   at
com.leinardi.pycharm.pylint.checker.ScanFiles.call(ScanFiles.java:74)   at
com.leinardi.pycharm.pylint.checker.ScanFiles.call(ScanFiles.java:46)   at
com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:265)   at
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)   at
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)   at
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)   at
java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)   at
java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)   at
java.base/java.security.AccessController.doPrivileged(Native Method)   at
java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)   at
java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by kavanase** [comment]
Hi!
I'm also getting the same error notifications, on `PyCharm.2022.3.1` with `pylint` 2.15.0, plugin 0.14.0 and python 3.8. Is there any update or solution to this?

**Comment by leinardi** [comment]
Hi everyone,  

A new developer, `@szabope`, has created a full rewrite of this PyLint plugin. The new plugin is actively maintained and addresses many of the issues found here.  

You can find the new plugin on the JetBrains Plugin Marketplace: [PyLint Plugin](https://plugins.jetbrains.com/plugin/26358-pylint/versions/stable/668924) 
The source code is available here: [GitHub Repository](https://github.com/szabope/pylint-pycharm-plugin)

Please give it a try, as the old plugin will soon be archived.  

Thank you!
