### ISSUE TITLE
java.io.IOException: CreateProcess error=206, The filename or extension is too long

### ISSUE THREAD

**Issue by fabiopedrosa** [leinardi/pylint-pycharm#76]
Whenever I try to run the plugin for the whole project, I always get this:

```
The scan failed due to an exception: Error creating Pylint process Root cause: CreateProcess error=206, The filename or extension is too long java.io.IOException: CreateProcess error=206, The filename or extension is too long   at java.base/java.lang.ProcessImpl.create(Native Method)   at java.base/java.lang.ProcessImpl. (ProcessImpl.java:478)   at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)   at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)   at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)   at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:457)   at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:422)   at com.leinardi.pycharm.pylint.plapi.PylintRunner.scan(PylintRunner.java:274)   at com.leinardi.pycharm.pylint.checker.ScanFiles.scan(ScanFiles.java:108)   at com.leinardi.pycharm.pylint.checker.ScanFiles.checkFiles(ScanFiles.java:100)   at com.leinardi.pycharm.pylint.checker.ScanFiles.call(ScanFiles.java:74)   at com.leinardi.pycharm.pylint.checker.ScanFiles.call(ScanFiles.java:46)   at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:268)   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)   at java.base/java.security.AccessController.doPrivileged(Native Method)   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)   at java.base/java.lang.Thread.run(Thread.java:834)
```

Where can I find more info on this?

**Comment by gpcimino** [comment]
Any update on this?

**Comment by heidenbloed** [comment]
I had the same problem. Marking a virtual environment folder as excluded dictionary solved the problem for me. Maybe your project contains files with a very long path that you need to exclude.
