### ISSUE TITLE
Pylint 3.0.0a1 crash

### ISSUE THREAD

**Issue by baterflyrity** [leinardi/pylint-pycharm#79]
>Ok, let's debug it together then :) Can you open a pylint issue with the pylint >command launched just before the crash and the code on which it was launched ?
>
>_Originally posted by @Pierre-Sassoulas in https://github.com/leinardi/pylint-pycharm/issues/41#issuecomment-810166482_

**Comment by baterflyrity** [comment]
step 1: press start button
step 2: wait until scanning is finished

![изображение](https://user-images.githubusercontent.com/15788974/112989211-5648b380-916d-11eb-8faa-04c6b36092d4.png)

error:

![изображение](https://user-images.githubusercontent.com/15788974/112989334-76787280-916d-11eb-8ad7-fb31ff206951.png)

```
The scan failed due to an exception: An error occurred while scanning a file. Root cause: null 
java.lang.NullPointerException   at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:98)   at 
java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)   at 
java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)   at 
java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)   at 
java.base/java.nio.file.Path.of(Path.java:147)   at java.base/java.nio.file.Paths.get(Paths.java:69)   at 
com.leinardi.pycharm.pylint.plapi.ProcessResultsThread.normalisePath(ProcessResultsThread.java:117)   at 
com.leinardi.pycharm.pylint.plapi.ProcessResultsThread.filenameFrom(ProcessResultsThread.java:111)   at 
com.leinardi.pycharm.pylint.plapi.ProcessResultsThread.run(ProcessResultsThread.java:86)   at 
com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:860)   at 
com.leinardi.pycharm.pylint.checker.ScanFiles.scan(ScanFiles.java:120)   at 
com.leinardi.pycharm.pylint.checker.ScanFiles.checkFiles(ScanFiles.java:100)   at 
com.leinardi.pycharm.pylint.checker.ScanFiles.call(ScanFiles.java:74)   at 
com.leinardi.pycharm.pylint.checker.ScanFiles.call(ScanFiles.java:46)   at 
com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:270)   at 
java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)   at 
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)   at 
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)   at 
java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)   at 
java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)   at 
java.base/java.security.AccessController.doPrivileged(Native Method)   at 
java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)   at 
java.base/java.lang.Thread.run(Thread.java:834)
```

code:

```python
print('Hello, world')
```

**Comment by leinardi** [comment]
I guess @Pierre-Sassoulas suggestion's was to open an issue on the official PyLint issue tracker: https://github.com/PyCQA/pylint/issues

**Comment by baterflyrity** [comment]
@leinardi I dont know. Let ask him) @Pierre-Sassoulas, hey, what did u mean?

**Comment by Pierre-Sassoulas** [comment]
Yeah, sorry I was not very clear. If it's a crash inside pylint the issue could be opened in https://github.com/PyCQA/pylint/issues. I would need the actual pylint command launched by `pylint-pycharm` for this file in order to do something about the crash. Maybe something like `pylint -sy -rn ... hello_world.py`. I do not have the knowledge to debug pylint-pycharm directly.

**Comment by baterflyrity** [comment]
@Pierre-Sassoulas, Thanks for help but i dont know command((

**Comment by leinardi** [comment]
@baterflyrity you should be able to find the pylint command inside the [PyCharm log files](https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files), just look for the text `Command Line string`:

![image](https://user-images.githubusercontent.com/273338/112996375-68762200-916c-11eb-8b5d-320efee6ffea.png)

**Comment by Pierre-Sassoulas** [comment]
The thing is we did not release this in 2.x version because having `--score=yes` would not output score. So breaking thing is expected when suddenly pylint output the score. It's entirely possible that `pylint-pycharm` now breaks because the newly added score is not parsed correctly.

**Comment by baterflyrity** [comment]
@leinardi , what is really surprising is that in log no pylint command is stated anywhere.

**Comment by baterflyrity** [comment]
Consider updating pylint version bundled with the plugin to actual one from pypi (it is 2.10.2 but 3.*).

**Comment by leinardi** [comment]
Hi everyone,  

A new developer, `@szabope`, has created a full rewrite of this PyLint plugin. The new plugin is actively maintained and addresses many of the issues found here.  

You can find the new plugin on the JetBrains Plugin Marketplace: [PyLint Plugin](https://plugins.jetbrains.com/plugin/26358-pylint/versions/stable/668924) 
The source code is available here: [GitHub Repository](https://github.com/szabope/pylint-pycharm-plugin)

Please give it a try, as the old plugin will soon be archived.  

Thank you!
