### ISSUE TITLE
Fails to find pylint.exe on relative path since PyCharm 2023.2.1 

### ISSUE THREAD

**Issue by f-pa-u-li** [leinardi/pylint-pycharm#99]
### Step 1: Are you in the right place?
- [ x] I have verified there are no duplicate active or recent bugs, questions, or requests
- [x ] I have verified that I am using the latest version of the plugin.

### Step 2: Describe your environment
 - Plugin version: 0.16.0
 - PyCharm/IDEA version: 2023.2.1 
 - Pylint version: 2.15.0

### Step 3: Describe the problem:
Relative prodce an error log (see below) if I try to run pylint and its location is defined by a relative path even though clicken on the "test"-button in the Pylint-configuration returns a "success-message". This occurs since I updated to pyCharm 2023.2.1
#### Steps to reproduce:

  1. Enter a (correct) rrelative path into the textbox "path to pylint executable"
  2. click Apply and Ok
  3. Run "check current file

error Log : 
The scan failed due to an exception: Error creating Pylint process Root cause: CreateProcess error=2, Das System kann die angegebene Datei nicht finden java.io.IOException: CreateProcess error=2, Das System kann die angegebene Datei nicht finden   at java.base/java.lang.ProcessImpl.create(Native Method)   at java.base/java.lang.ProcessImpl. (ProcessImpl.java:499)   at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)   at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)   at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)   at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:432)   at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:346)   at com.leinardi.pycharm.pylint.plapi.PylintRunner.scan(PylintRunner.java:270)   at com.leinardi.pycharm.pylint.checker.ScanFiles.scan(ScanFiles.java:109)   at com.leinardi.pycharm.pylint.checker.ScanFiles.checkFiles(ScanFiles.java:100)   at com.leinardi.pycharm.pylint.checker.ScanFiles.call(ScanFiles.java:74)   at com.leinardi.pycharm.pylint.checker.ScanFiles.call(ScanFiles.java:46)   at com.intellij.openapi.application.impl.ApplicationImpl$3.call(ApplicationImpl.java:303)   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)   at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)   at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)   at java.base/java.lang.Thread.run(Thread.java:833

**Comment by leinardi** [comment]
Hi everyone,  

A new developer, `@szabope`, has created a full rewrite of this PyLint plugin. The new plugin is actively maintained and addresses many of the issues found here.  

You can find the new plugin on the JetBrains Plugin Marketplace: [PyLint Plugin](https://plugins.jetbrains.com/plugin/26358-pylint/versions/stable/668924) 
The source code is available here: [GitHub Repository](https://github.com/szabope/pylint-pycharm-plugin)

Please give it a try, as the old plugin will soon be archived.  

Thank you!
